services:
  hw3:
    image: compilerdesign/compiler-design-2026-hw3
    platform: linux/amd64
    network_mode: none
    volumes:
      - ./src:/hw3/src
      - ./testcases:/hw3/testcases
    stdin_open: true
    tty: true
    command: run_test
